# Generated by Django 3.1.5 on 2021-06-13 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quicktrack', '0002_auto_20210609_2359'),
        ('runcitworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sales_target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quicktrack.account'),
        ),
    ]
