# Generated by Django 3.1.5 on 2021-06-13 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quicktrack', '0002_auto_20210609_2359'),
        ('runcitworks', '0003_auto_20210613_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sales_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quicktrack.account'),
        ),
    ]
