# Generated by Django 3.2.4 on 2021-06-26 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('runcitworks', '0006_auto_20210626_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previousbalance',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='runcitworks.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='runcitworks.product'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='runcitworks.product'),
        ),
    ]
