# Generated by Django 3.2.8 on 2021-12-03 03:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('runcitworks', '0008_auto_20210629_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=128)),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10000000)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('monthdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='runcitworks.monthdata')),
            ],
        ),
    ]
